sudo: required
services:
  - docker
language: node_js
node_js:
  - "6"
after_success:
  - "echo \"module.exports = {datadog: '$DATADOG',cdnUrl: '//gg.fuechschen.space',httpPort: 3000};\" > config.js"
  - npm run production
  - docker build -t fuechschen/kitsune-website .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push fuechschen/kitsune-website && exit 0