sudo: required
services:
  - docker
language: node_js
node_js:
  - "6"
after_script:
  - "echo \"module.exports = {datadog: '$DATADOG',cdnUrl: '//gg.fuechschen.space',httpPort: 4236};\" > config.js"
  - docker build -t kitsune/website .
  - docker login registry.fuechschen.org
  - docker push kitsune/website