sudo: required
services:
  - docker
language: node_js
node_js:
  - "6"
after_success:
  - "echo \"module.exports = {datadog: process.env.DATADOG,cdnUrl: '//gg.fuechschen.space',httpPort: 3000};\" > config.js"
  - npm run production
  - docker build -t registry.fuechschen.org/fuechschen/kitsune-website .
  - docker login registry.fuechschen.org -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push registry.fuechschen.org/fuechschen/kitsune-website && exit 0